# Generated by Django 2.1.2 on 2018-10-15 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=10)),
                ('friend_name_list', models.ManyToManyField(related_name='_students_friend_name_list_+', to='info.Students')),
                ('student_school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.School')),
            ],
        ),
    ]
